AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'

Resources:
  DatalogFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: datalog.lambda_handler
      Runtime: python3.6
      CodeUri: lambda/datalog.py
      Timeout: 15
      MemorySize: 256
      Policies: AWSLambdaKinesisExecutionRole
      Events:
        StreamData:
          Type: Kinesis
          Properties:
            Stream: !GetAtt DataStream.Arn
            BatchSize: 50
            StartingPosition: TRIM_HORIZON



  DataStream:
    Type: AWS::Kinesis::Stream
    Properties:
      Name: datastream
      ShardCount: 1
      Tags:
        -
          Key: 'Project'
          Value: 'SEIS665'
          
  DatapipeTable:
    Type: 'AWS::Serverless::SimpleTable'
    Properties:
      PrimaryKey:
        Name: id
        Type: String
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      SSESpecification:
        SSEEnabled: true
        
  DatastoreFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: datastore.lambda_handler
      Runtime: python3.6
      CodeUri: lambda/datastore.py
      Timeout: 15
      MemorySize: 256
      Policies: AWSLambdaFullAccess
      Environment:
        Variables:
          TABLE_NAME: !GetAtt DatapipeTable.Arn
      Events:
        StreamData:
          Type: Kinesis
          Properties:
            Stream: !GetAtt DataStream.Arn
            BatchSize: 50
            StartingPosition: TRIM_HORIZON
