pipeline { 
    agent { label 'linux' }
    stages { 
        stage ("Linting") {
          steps { 
            sh 'flake8 app/site.py'
          }
        }
        stage ("Build") {
          steps { 
              sh 'docker build -t classweb:${BUILD_NUMBER} .'
          }
        }
        stage ("Test") {
          steps { 
              sh 'docker run -d -p 80:8080 --name classweb1 classweb:${BUILD_NUMBER}'
              sh 'curl --ipv4 $(curl 169.254.169.254/latest/meta-data/local-ipv4) | grep "super"'
          }
        }
    }
    post {
            always {
                script {
                      if (sh(returnStdout: true, script: 'docker ps -q --filter "name=classweb1"')) {
                        sh 'docker stop $(docker ps -q --filter "name=classweb1")'
                      }
                      if (sh(returnStdout: true, script: 'docker ps -q -a --filter "name=classweb1"')) {
                        sh 'docker rm $(docker ps -q -a --filter "name=classweb1")'
                      }
                }
            }
    }
}
